version: '3.8'

services:
  nginx-rtmp-service:
    build: ./docker/nginx_rtmp
    container_name: nginx-rtmp-service
    ports:
      - "${NGINX_RTMP_PORT}:1935"
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ${NGINX_HLS_VOLUME_PATH}:/tmp/hls
    restart: always
